package fr.twiloo.iut.gtes.common;

public enum Action {
    NOUVELLE_EQUIPE_CREE,
    EQUIPE_SUPPRIMEE,
    EQUIPE_MODIFIEE,
    MATCH_ORGANISE,
    MATCH_TERMINE,
    MATCH_ANNULE,
    NOTIFICATION_MATCH_TERMINE,
    NOTIFICATION_NOUVELLE_EQUIPE
}
