package fr.twiloo.iut.gtes.common;

public enum EventType {
    GET_TEAMS_LIST,
    SHOW_TEAMS_LIST,
    CREATE_TEAM,
    NEW_TEAM_CREATED,
    UPDATE_TEAM,
    TEAM_UPDATED,
    DELETE_TEAM,
    TEAM_DELETED,
    CREATE_MATCH,
    NEW_MATCH_CREATED,
    CANCEL_MATCH,
    MATCH_CANCELED,
    SET_MATCH_RESULTS,
    MATCH_FINISHED,
    RANKING_UPDATED,
}
